### ISSUE TITLE
[Feature Request] Material TextView

### ISSUE THREAD

**Issue by gwartnes** [Akylas/nativescript-material-components#13]
Great work on this awesome package! I know there are a lot of Material components and recreating them all in ns takes time. One that would be really helpful would be a Material TextView (the metaphor from web would be textarea)

**Comment by farfromrefug** [comment]
@gwartnes it s just a "multi line" textfield, so should be doable. Will look at it when i have time

**Comment by sebj54** [comment]
Hi! 

Any updates on this? It's sad to have a different style for TextViews actually, any recommandation on how to implement it or any workaround?

Thanks for your help!

**Comment by farfromrefug** [comment]
No time to implement yet. PRs are welcome:
* ios impl https://github.com/material-components/material-components-ios/tree/develop/components/TextFields#examples---multi-line
* android maybe this ? https://stackoverflow.com/a/31851990/993813

**Comment by Logikgate** [comment]
@farfromrefug I have started to make the TextView component with your suggestions above. [repo](https://github.com/flypapertech/nativescript-material-components/tree/TextView)

It compiles and renders a multi line text field on iOS but the floating placeholder just stays a part of the text you type into it and all of the text is grey rather than the default black.  It may be because it doesn't look like Nativescript's TextView has a _updateAttributedPlaceholder method like TextField does but I'm unsure what to replace that with.

I have very little native mobile experience so I am unsure where to go from here.  I'll continue to try to debug it but if you or someone else with more knowledge than me could take a look that would be a big help

![Screen Shot 2019-12-20 at 7 08 57 PM](https://user-images.githubusercontent.com/2379994/71299635-62d04080-235c-11ea-986e-5bd4e94ec36e.png)

**Comment by farfromrefug** [comment]
@Logikgate great to see you have a look at this. About your issue on ios. First make sure you are using a recent version of the Material Components pod. May try anther version to see if the bug is still there. You can search on their github too. I think the issue comes from there.

**Comment by Logikgate** [comment]
Alright, I've got it working on iOS. The problem stemmed from extending Nativescript's TextView implementation. They have it hard coded to hide the placeholder based on if there is text or not.

I've added to the demo and it builds on iOS but I am running into errors when trying to run the android version. I'm not sure if it's a problem with my environment or with the implementation since I'm in general having problems with android. Could you clone my branch and try to run the android demo to see if it works for you?  [Repo](https://github.com/flypapertech/nativescript-material-components/tree/TextView)

![Screen Shot 2019-12-23 at 6 04 12 PM](https://user-images.githubusercontent.com/2379994/71384321-a1f5d000-25ae-11ea-8b74-bc5fb7f3d522.png)

**Comment by farfromrefug** [comment]
@Logikgate Can you create the PR? Even if you keep on making commits. Easier for me to work from

**Comment by Raina-Rishab** [comment]
I am not able to change the height of <MDTextView> only width is editable, I am also not getting a multi-line textview, kindly help? 
the code looks like:

**package.json**
      "@nativescript-community/ui-material-core": "^6.2.14",
    "@nativescript-community/ui-material-floatingactionbutton": "^6.2.14",
    "@nativescript-community/ui-material-textview": "^6.2.14",
**component.html**

<DockLayout stretchLastChild="true">
     <StackLayout dock="top" height="30%" backgroundColor="yellow">
        <Label  text="login credentials"></Label>
        <MDButton  rippleColor="pink" text="text button"></MDButton>
     </StackLayout>
    <StackLayout dock="top" height="20%" backgroundColor="green">
        <MDFloatingActionButton  rippleColor="blue" src="res://ic_star"></MDFloatingActionButton>
    </StackLayout>
    <StackLayout dock="bottom" backgroundColor="red" >
        <MDTextView height="100%"  variant="outline" helper="example helper" placeholderColor="grey" keyboardType="email"
        hint="description" returnKeyType="done" (focus)="onFocus($event)" (blur)="onBlur($event)"
        (textChange)="onTextChange($event)">
        
   
    </MDTextView>
    </StackLayout>
    
 </DockLayout>
