### ISSUE TITLE
ng textfield styling

### ISSUE THREAD

**Issue by mchallenger88** [Akylas/nativescript-material-components#65]
How do we style the various elements of the textfield?

For example, the filled version is medium-light gray and the hint is white when it animates to the top. The gray is not bad but it would be nice to change it. And the white hint text after animation is completely unreadable. Seems like that should be an off black.

**Comment by diegovincent** [comment]
@farfromrefug is there any way to change the font size of the hint text after the animation has taken place?

**Comment by farfromrefug** [comment]
@diegovincent not right now it dont think. Need to see how to do it natively then make a PR

**Comment by diegovincent** [comment]
@farfromrefug I have a question regarding the TextField / TextView. Is there any way to react to the tap event? When I use the `tap` event from NativeScript using NativeScript Angular, it only reacts to the tap event when I click on the `hint` text, not when I focus on the field, which should be able to count as tap?

I would use focus, but I want the user to be able to tap several times the field, because it actually opens a modal, so they can focus, close the modal by accident and then tap again, but since it is already focused, it would not work.

Could you help me with this?

**Comment by farfromrefug** [comment]
@diegovincent must be a native behavior. I dont do anything special there. The native comp must be intercepting the touch event thus preventing you from getting the tap event.

**Comment by diegovincent** [comment]
> @diegovincent must be a native behavior. I dont do anything special there. The native comp must be intercepting the touch event thus preventing you from getting the tap event.

That actually makes a lot of sense, what do you recommend?

**Comment by farfromrefug** [comment]
You want to open a modal when clicking a textfield? Not sure it  makes sense. Is it a search text field? Maybe you should use a label? Or make make the text field non editable?

**Comment by diegovincent** [comment]
@farfromrefug I want to open a modal that shows a modal dialog, that contains a list picker, when they tap on the MDTextView labeled as "Countries". Also, the text field is already non-editable. It works with a standard label and even text field, it just fails with the plugin, but I want to use the plugin because of the hint or placeholder animation.

**Comment by farfromrefug** [comment]
ok so disable user interaction on the textfield, put a transparent view on top, and register the tap event on that view.
