### ISSUE TITLE
nativescript-material-floatingactionbutton text attribute

### ISSUE THREAD

**Issue by inONEL** [Akylas/nativescript-material-components#93]
text attribute is not working as expected in the floatingactionbutton. 
Android crashes when using a text attribute.

IOS doesn't crash but has weird behaviour. I am using material icon as text in the button on IOS it initially shows the right icon but when I tap the button the icon changes in an image of a lock.

**Comment by farfromrefug** [comment]
@inONEL can you post a sample, logs, versions ... 
BTW FAB dont work with text, they work with images.
https://github.com/Akylas/nativescript-material-components/tree/master/packages/nativescript-material-floatingactionbutton

**Comment by inONEL** [comment]
In the documentation it says:
Inherite from Nativescript Button so it already has all the same attributes
So it should also have the ability to use text since this is an attribute on the Nativescript Button

`  <MDFloatingActionButton (tap)="tapEvent()" verticalAlignment="bottom" horizontalAlignment="right" height="50" width="50" src="~/assets/img/baseline_add_white_18dp.png">
  </MDFloatingActionButton>`

This works. Problem is that the image is not centered on android.

`  <MDFloatingActionButton (tap)="tapEvent()" verticalAlignment="bottom" horizontalAlignment="right" height="50" width="50" text="mdi-add" class="mdi">
  </MDFloatingActionButton>`

The above code works in IOS. The only weird thing is when I tap the button the icon changes in to an image of a lock.

Throughout my application I use material font icon for all the images it is working everywhere as expected also in regular buttons.

**Comment by farfromrefug** [comment]
@inONEL my bad about the doc saying it inherits Button. It actually does but i need to make the "text" property not work to prevent your error.

Now about the centering issue can you create a sample project so that i can test it.

Now myself don't like to use the floatingactionbutton class because it uses images and i like to use icon fonts.
Here is  the way i do it
https://github.com/Akylas/nativescript-material-components/blob/master/demo-vue/app/examples/Buttons.vue#L29

**Comment by inONEL** [comment]
Thanks I'll try your suggestion since I also like to use icon fonts
